### PR TITLE
Upgrade MySQL to 9.0 and Switch InfluxDB to 1.8 for M1 Compatibility

### LINKED ISSUE #552: MySQL tests failing on Apple Silicon M1 with OpenBao
**Describe the bug**
When running `make test`, MySQL-related tests fail due to connection errors, specifically 'connection refused' on port 3306.

**To Reproduce**

1. Run `make test`
2. See error:
<details>
    <summary>Other tests output</summary>

```
    ==> Checking that build is using go version >= 1.22.6...
    ==> Using go version 1.23.1...
    go: not generating in packages in dependency modules
    go: not generating in packages in dependency modules
    ?       github.com/openbao/openbao/builtin/audit/socket [no test files]
    ?       github.com/openbao/openbao/builtin/audit/syslog [no test files]
    ?       github.com/openbao/openbao/builtin/credential/approle/cmd/approle       [no test files]
    ok      github.com/openbao/openbao      (cached) [no tests to run]
    ?       github.com/openbao/openbao/builtin/credential/cert/cmd/cert     [no test files]
    ok      github.com/openbao/openbao/audit        (cached)
    ok      github.com/openbao/openbao/builtin/audit/file   (cached)
    ok      github.com/openbao/openbao/builtin/credential/approle   (cached)
    ok      github.com/openbao/openbao/builtin/credential/cert      (cached)
    ok      github.com/openbao/openbao/builtin/credential/jwt       (cached)
    ?       github.com/openbao/openbao/builtin/credential/jwt/cmd/jwt       [no test files]
    ?       github.com/openbao/openbao/builtin/credential/kerberos/cmd/kerberos     [no test files]
    ?       github.com/openbao/openbao/builtin/credential/kerberos/cmd/login-kerb   [no test files]
    ok      github.com/openbao/openbao/builtin/credential/kerberos  (cached)
    ?       github.com/openbao/openbao/builtin/credential/kubernetes/cmd/kubernetes [no test files]
    ?       github.com/openbao/openbao/builtin/credential/ldap/cmd/ldap     [no test files]
    ok      github.com/openbao/openbao/builtin/credential/kubernetes        (cached)
    ok      github.com/openbao/openbao/builtin/credential/ldap      (cached)
    ok      github.com/openbao/openbao/builtin/credential/radius    (cached)
    ?       github.com/openbao/openbao/builtin/credential/radius/cmd/radius [no test files]
    ?       github.com/openbao/openbao/builtin/credential/token     [no test files]
    ?       github.com/openbao/openbao/builtin/credential/userpass/cmd/userpass     [no test files]
    ok      github.com/openbao/openbao/builtin/credential/userpass  (cached)
    ?       github.com/openbao/openbao/builtin/logical/kubernetes/cmd/kubernetes    [no test files]
    ok      github.com/openbao/openbao/builtin/logical/database     (cached)
    ?       github.com/openbao/openbao/builtin/logical/kv/cmd/kv    [no test files]
    ok      github.com/openbao/openbao/builtin/logical/database/dbplugin    (cached)
    ok      github.com/openbao/openbao/builtin/logical/kubernetes   (cached)
    ok      github.com/openbao/openbao/builtin/logical/kv   (cached)
    ok      github.com/openbao/openbao/builtin/logical/openldap     (cached)
    ok      github.com/openbao/openbao/builtin/logical/openldap/client      (cached)
    ?       github.com/openbao/openbao/builtin/logical/openldap/client/tools        [no test files]
    ?       github.com/openbao/openbao/builtin/logical/openldap/cmd/openldap        [no test files]
    ?       github.com/openbao/openbao/builtin/logical/openldap/ldapifc     [no test files]
    ?       github.com/openbao/openbao/builtin/logical/pki/cmd/pki  [no test files]
    ?       github.com/openbao/openbao/builtin/logical/pki/dnstest  [no test files]
    ?       github.com/openbao/openbao/builtin/logical/rabbitmq/cmd/rabbitmq        [no test files]
    ?       github.com/openbao/openbao/builtin/logical/ssh/cmd/ssh  [no test files]
    ok      github.com/openbao/openbao/builtin/logical/pki  (cached)
    ok      github.com/openbao/openbao/builtin/logical/pkiext       (cached)
    ok      github.com/openbao/openbao/builtin/logical/pkiext/pkiext_binary (cached)
    ok      github.com/openbao/openbao/builtin/logical/rabbitmq     (cached)
    ok      github.com/openbao/openbao/builtin/logical/ssh  (cached)
    ok      github.com/openbao/openbao/builtin/logical/totp (cached)
    ?       github.com/openbao/openbao/builtin/logical/totp/cmd/totp        [no test files]
    ?       github.com/openbao/openbao/builtin/logical/transit/cmd/transit  [no test files]
    ?       github.com/openbao/openbao/builtin/plugin/v5    [no test files]
    ok      github.com/openbao/openbao/builtin/logical/transit      (cached)
    ok      github.com/openbao/openbao/builtin/plugin       (cached)
    ?       github.com/openbao/openbao/command/agent/exec/test-app  [no test files]
    ?       github.com/openbao/openbao/command/agent/internal/ctmanager     [no test files]
    ?       github.com/openbao/openbao/command/agentproxyshared/auth/approle        [no test files]
    ok      github.com/openbao/openbao/command      (cached)
    ok      github.com/openbao/openbao/command/agent        (cached)
    ok      github.com/openbao/openbao/command/agent/config (cached)
    ok      github.com/openbao/openbao/command/agent/exec   (cached)
    ok      github.com/openbao/openbao/command/agent/template       (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared     (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared/auth        (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared/auth/cert   (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared/auth/jwt    (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared/auth/kerberos       (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared/auth/kubernetes     (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared/auth/token-file     (cached)
    ?       github.com/openbao/openbao/command/agentproxyshared/sink        [no test files]
    ?       github.com/openbao/openbao/command/agentproxyshared/sink/inmem  [no test files]
    ?       github.com/openbao/openbao/command/agentproxyshared/sink/mock   [no test files]
    ?       github.com/openbao/openbao/command/agentproxyshared/winsvc      [no test files]
    ?       github.com/openbao/openbao/command/healthcheck  [no test files]
    ok      github.com/openbao/openbao/command/agentproxyshared/cache       (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared/cache/cacheboltdb   (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared/cache/cachememdb    (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared/cache/keymanager    (cached)
    ok      github.com/openbao/openbao/command/agentproxyshared/sink/file   (cached)
    ok      github.com/openbao/openbao/command/config       (cached)
    ok      github.com/openbao/openbao/command/proxy/config (cached)
    ?       github.com/openbao/openbao/command/test-backend [no test files]
    ?       github.com/openbao/openbao/helper/benchhelpers  [no test files]
    ok      github.com/openbao/openbao/command/server       (cached)
    ok      github.com/openbao/openbao/command/token        (cached)
    ok      github.com/openbao/openbao/helper/builtinplugins        (cached)
    ok      github.com/openbao/openbao/helper/dhutil        (cached) [no tests to run]
    ok      github.com/openbao/openbao/helper/fairshare     (cached)
    ok      github.com/openbao/openbao/helper/flag-kv       (cached)
    ok      github.com/openbao/openbao/helper/flag-slice    (cached)
    ok      github.com/openbao/openbao/helper/forwarding    (cached)
    ?       github.com/openbao/openbao/helper/identity      [no test files]
    ?       github.com/openbao/openbao/helper/identity/mfa  [no test files]
    ?       github.com/openbao/openbao/helper/locking       [no test files]
    ok      github.com/openbao/openbao/helper/hostutil      (cached)
    ok      github.com/openbao/openbao/helper/logging       (cached)
    ok      github.com/openbao/openbao/helper/metricsutil   (cached)
    ok      github.com/openbao/openbao/helper/monitor       (cached)
    ok      github.com/openbao/openbao/helper/namespace     (cached)
    ok      github.com/openbao/openbao/helper/osutil        (cached)
    ok      github.com/openbao/openbao/helper/parseip       (cached)
    ?       github.com/openbao/openbao/helper/proxyutil     [no test files]
    ok      github.com/openbao/openbao/helper/pgpkeys       (cached)
    ok      github.com/openbao/openbao/helper/policies      (cached)
    ok      github.com/openbao/openbao/helper/random        (cached)
    ?       github.com/openbao/openbao/helper/testhelpers   [no test files]
    ok      github.com/openbao/openbao/helper/storagepacker (cached)
    ?       github.com/openbao/openbao/helper/testhelpers/cassandra [no test files]
    ?       github.com/openbao/openbao/helper/testhelpers/certhelpers       [no test files]
    ?       github.com/openbao/openbao/helper/testhelpers/corehelpers       [no test files]
    ?       github.com/openbao/openbao/helper/testhelpers/ldap      [no test files]
    ?       github.com/openbao/openbao/helper/testhelpers/mysql     [no test files]
    ?       github.com/openbao/openbao/helper/testhelpers/pluginhelpers     [no test files]
    ?       github.com/openbao/openbao/helper/testhelpers/postgresql        [no test files]
    ok      github.com/openbao/openbao/helper/testhelpers/logical   (cached)
    ?       github.com/openbao/openbao/helper/testhelpers/seal      [no test files]
    ?       github.com/openbao/openbao/helper/testhelpers/teststorage       [no test files]
    ok      github.com/openbao/openbao/helper/timeutil      (cached)
    ok      github.com/openbao/openbao/helper/useragent     (cached)
    ok      github.com/openbao/openbao/helper/versions      (cached)
    ok      github.com/openbao/openbao/http (cached)
    ok      github.com/openbao/openbao/internalshared/configutil    (cached)
    ok      github.com/openbao/openbao/internalshared/listenerutil  (cached)
    ok      github.com/openbao/openbao/physical/postgresql  (cached)
    ok      github.com/openbao/openbao/physical/raft        (cached)
    ?       github.com/openbao/openbao/plugins/database/cassandra/cassandra-database-plugin [no test files]
    ?       github.com/openbao/openbao/plugins/database/influxdb/influxdb-database-plugin   [no test files]
    ok      github.com/openbao/openbao/plugins/database/cassandra   (cached)
    ok      github.com/openbao/openbao/plugins/database/influxdb    (cached)
    ?       github.com/openbao/openbao/plugins/database/mysql/mysql-database-plugin [no test files]
    ?       github.com/openbao/openbao/plugins/database/mysql/mysql-legacy-database-plugin  [no test files]
    ?       github.com/openbao/openbao/plugins/database/postgresql/postgresql-database-plugin       [no test files]
    ?       github.com/openbao/openbao/serviceregistration  [no test files]
    ?       github.com/openbao/openbao/serviceregistration/kubernetes/client/cmd/kubeclient [no test files]
    ?       github.com/openbao/openbao/serviceregistration/kubernetes/testing       [no test files]
    ?       github.com/openbao/openbao/tools/codechecker    [no test files]
    ?       github.com/openbao/openbao/vault/tokens [no test files]
    ?       github.com/openbao/openbao/version      [no test files]
    ?       github.com/openbao/openbao/sdk/v2/database/dbplugin     [no test files]
    ?       github.com/openbao/openbao/sdk/v2/database/dbplugin/v5/proto    [no test files]
    ?       github.com/openbao/openbao/sdk/v2/database/dbplugin/v5/testing  [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/base62 [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/consts [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/dbtxn  [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/docker [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/errutil        [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/hclutil        [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/license        [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/mlock  [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/parseutil      [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/password       [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/pointerutil    [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/stepwise/environments/docker   [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/strutil        [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/testcluster    [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/testcluster/docker     [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/tlsutil        [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/tokenutil      [no test files]
    ?       github.com/openbao/openbao/sdk/v2/helper/wrapping       [no test files]
    ?       github.com/openbao/openbao/sdk/v2/physical      [no test files]
```

</details>

```
--- FAIL: TestMySQL_Initialize (0.01s)
    --- FAIL: TestMySQL_Initialize/non-special_characters_in_root_password (0.01s)
        --- FAIL: TestMySQL_Initialize/non-special_characters_in_root_password/basic_config (0.01s)
            mysql_test.go:164: no error expected, got: error verifying - ping: dial tcp [::1]:3306: connect: connection refused
        --- FAIL: TestMySQL_Initialize/non-special_characters_in_root_password/username_and_password_replacement_in_connection_url (0.00s)
            mysql_test.go:164: no error expected, got: error verifying - ping: dial tcp [::1]:3306: connect: connection refused
        --- FAIL: TestMySQL_Initialize/non-special_characters_in_root_password/custom_username_template (0.00s)
            mysql_test.go:164: no error expected, got: error verifying - ping: dial tcp [::1]:3306: connect: connection refused
    --- FAIL: TestMySQL_Initialize/special_characters_in_root_password (0.00s)
        --- FAIL: TestMySQL_Initialize/special_characters_in_root_password/custom_username_template (0.00s)
            mysql_test.go:164: no error expected, got: error verifying - ping: dial tcp [::1]:3306: connect: connection refused
        --- FAIL: TestMySQL_Initialize/special_characters_in_root_password/basic_config (0.00s)
            mysql_test.go:164: no error expected, got: error verifying - ping: dial tcp [::1]:3306: connect: connection refused
        --- FAIL: TestMySQL_Initialize/special_characters_in_root_password/username_and_password_replacement_in_connection_url (0.00s)
            mysql_test.go:164: no error expected, got: error verifying - ping: dial tcp [::1]:3306: connect: connection refused
--- FAIL: TestMySQL_NewUser_nonLegacy (0.00s)
    --- FAIL: TestMySQL_NewUser_nonLegacy/name_statements (0.00s)
        mysql_test.go:309: 
                Error Trace:    /Users/fatima/openbao/plugins/database/mysql/mysql_test.go:309
                Error:          Received unexpected error:
                                error verifying - ping: dial tcp [::1]:3306: connect: connection refused
                Test:           TestMySQL_NewUser_nonLegacy/name_statements
    --- FAIL: TestMySQL_NewUser_nonLegacy/username_statements (0.00s)
        mysql_test.go:309: 
                Error Trace:    /Users/fatima/openbao/plugins/database/mysql/mysql_test.go:309
                Error:          Received unexpected error:
                                error verifying - ping: dial tcp [::1]:3306: connect: connection refused
                Test:           TestMySQL_NewUser_nonLegacy/username_statements
    --- FAIL: TestMySQL_NewUser_nonLegacy/prepared_name_statements (0.00s)
        mysql_test.go:309: 
                Error Trace:    /Users/fatima/openbao/plugins/database/mysql/mysql_test.go:309
                Error:          Received unexpected error:
                                error verifying - ping: dial tcp [::1]:3306: connect: connection refused
                Test:           TestMySQL_NewUser_nonLegacy/prepared_name_statements
    --- FAIL: TestMySQL_NewUser_nonLegacy/prepared_username_statements (0.00s)
        mysql_test.go:309: 
                Error Trace:    /Users/fatima/openbao/plugins/database/mysql/mysql_test.go:309
                Error:          Received unexpected error:
                                error verifying - ping: dial tcp [::1]:3306: connect: connection refused
                Test:           TestMySQL_NewUser_nonLegacy/prepared_username_statements
    --- FAIL: TestMySQL_NewUser_nonLegacy/custom_username_template (0.00s)
        mysql_test.go:309: 
                Error Trace:    /Users/fatima/openbao/plugins/database/mysql/mysql_test.go:309
                Error:          Received unexpected error:
                                error verifying - ping: dial tcp [::1]:3306: connect: connection refused
                Test:           TestMySQL_NewUser_nonLegacy/custom_username_template
--- FAIL: TestMySQL_NewUser_legacy (0.00s)
    --- FAIL: TestMySQL_NewUser_legacy/custom_username_template (0.00s)
        mysql_test.go:463: 
                Error Trace:    /Users/fatima/openbao/plugins/database/mysql/mysql_test.go:463
                Error:          Received unexpected error:
                                error verifying - ping: dial tcp [::1]:3306: connect: connection refused
                Test:           TestMySQL_NewUser_legacy/custom_username_template
    --- FAIL: TestMySQL_NewUser_legacy/name_statements (0.00s)
        mysql_test.go:463: 
                Error Trace:    /Users/fatima/openbao/plugins/database/mysql/mysql_test.go:463
                Error:          Received unexpected error:
                                error verifying - ping: dial tcp [::1]:3306: connect: connection refused
                Test:           TestMySQL_NewUser_legacy/name_statements
    --- FAIL: TestMySQL_NewUser_legacy/username_statements (0.00s)
        mysql_test.go:463: 
                Error Trace:    /Users/fatima/openbao/plugins/database/mysql/mysql_test.go:463
                Error:          Received unexpected error:
                                error verifying - ping: dial tcp [::1]:3306: connect: connection refused
                Test:           TestMySQL_NewUser_legacy/username_statements
    --- FAIL: TestMySQL_NewUser_legacy/prepared_name_statements (0.00s)
        mysql_test.go:463: 
                Error Trace:    /Users/fatima/openbao/plugins/database/mysql/mysql_test.go:463
                Error:          Received unexpected error:
                                error verifying - ping: dial tcp [::1]:3306: connect: connection refused
                Test:           TestMySQL_NewUser_legacy/prepared_name_statements
    --- FAIL: TestMySQL_NewUser_legacy/prepared_username_statements (0.00s)
        mysql_test.go:463: 
                Error Trace:    /Users/fatima/openbao/plugins/database/mysql/mysql_test.go:463
                Error:          Received unexpected error:
                                error verifying - ping: dial tcp [::1]:3306: connect: connection refused
                Test:           TestMySQL_NewUser_legacy/prepared_username_statements
--- FAIL: TestMySQL_RotateRootCredentials (0.00s)
    --- FAIL: TestMySQL_RotateRootCredentials/empty_statements (0.00s)
        mysql_test.go:524: err: error verifying - ping: dial tcp [::1]:3306: connect: connection refused
    --- FAIL: TestMySQL_RotateRootCredentials/default_username (0.00s)
        mysql_test.go:524: err: error verifying - ping: dial tcp [::1]:3306: connect: connection refused
    --- FAIL: TestMySQL_RotateRootCredentials/default_name (0.00s)
        mysql_test.go:524: err: error verifying - ping: dial tcp [::1]:3306: connect: connection refused
--- FAIL: TestMySQL_DeleteUser (0.00s)
    mysql_test.go:601: err: error verifying - ping: dial tcp [::1]:3306: connect: connection refused
--- FAIL: TestMySQL_UpdateUser (0.00s)
    --- FAIL: TestMySQL_UpdateUser/empty_statements (0.00s)
        mysql_test.go:690: dial tcp [::1]:3306: connect: connection refused
    --- FAIL: TestMySQL_UpdateUser/custom_statement_name (0.00s)
        mysql_test.go:690: dial tcp [::1]:3306: connect: connection refused
    --- FAIL: TestMySQL_UpdateUser/custom_statement_username (0.00s)
        mysql_test.go:690: dial tcp [::1]:3306: connect: connection refused
FAIL
FAIL    github.com/openbao/openbao/plugins/database/mysql       1.333s
```

<details>
<summary>Other tests output</summary>

```
ok      github.com/openbao/openbao/plugins/database/postgresql  (cached)
ok      github.com/openbao/openbao/plugins/database/postgresql/scram    (cached)
ok      github.com/openbao/openbao/serviceregistration/kubernetes       (cached)
ok      github.com/openbao/openbao/serviceregistration/kubernetes/client        (cached)
ok      github.com/openbao/openbao/tools/codechecker/pkg/godoctests     (cached)
ok      github.com/openbao/openbao/tools/codechecker/pkg/gonilnilfunctions      (cached)
ok      github.com/openbao/openbao/vault        (cached)
ok      github.com/openbao/openbao/vault/cluster        (cached)
ok      github.com/openbao/openbao/vault/diagnose       (cached)
ok      github.com/openbao/openbao/vault/external_tests/api     (cached)
ok      github.com/openbao/openbao/vault/external_tests/approle (cached)
ok      github.com/openbao/openbao/vault/external_tests/expiration      (cached)
ok      github.com/openbao/openbao/vault/external_tests/identity        (cached)
ok      github.com/openbao/openbao/vault/external_tests/kv      (cached)
ok      github.com/openbao/openbao/vault/external_tests/metrics (cached)
ok      github.com/openbao/openbao/vault/external_tests/mfa     (cached)
ok      github.com/openbao/openbao/vault/external_tests/misc    (cached)
ok      github.com/openbao/openbao/vault/external_tests/misc/misc_binary        (cached)
ok      github.com/openbao/openbao/vault/external_tests/plugin  (cached)
ok      github.com/openbao/openbao/vault/external_tests/policy  (cached)
ok      github.com/openbao/openbao/vault/external_tests/pprof   (cached)
ok      github.com/openbao/openbao/vault/external_tests/pprof/pprof_binary      (cached)
ok      github.com/openbao/openbao/vault/external_tests/quotas  (cached)
ok      github.com/openbao/openbao/vault/external_tests/raft    (cached)
ok      github.com/openbao/openbao/vault/external_tests/raft/raft_binary        (cached)
ok      github.com/openbao/openbao/vault/external_tests/raftha  (cached)
ok      github.com/openbao/openbao/vault/external_tests/response        (cached)
ok      github.com/openbao/openbao/vault/external_tests/router  (cached)
ok      github.com/openbao/openbao/vault/external_tests/sealmigration   (cached)
ok      github.com/openbao/openbao/vault/external_tests/sealmigrationext        (cached)
ok      github.com/openbao/openbao/vault/external_tests/token   (cached)
ok      github.com/openbao/openbao/vault/external_tests/userpass_binary (cached)
ok      github.com/openbao/openbao/vault/quotas (cached)
ok      github.com/openbao/openbao/vault/seal   (cached)
ok      github.com/openbao/openbao/api/v2       (cached)
ok      github.com/openbao/openbao/sdk/v2/database/dbplugin/v5  (cached)
ok      github.com/openbao/openbao/sdk/v2/database/helper/connutil      (cached)
ok      github.com/openbao/openbao/sdk/v2/database/helper/credsutil     (cached)
ok      github.com/openbao/openbao/sdk/v2/database/helper/dbutil        (cached)
ok      github.com/openbao/openbao/sdk/v2/framework     (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/authmetadata   (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/certutil       (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/cidrutil       (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/compressutil   (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/cryptoutil     (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/custommetadata (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/identitytpl    (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/jsonutil       (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/kdf    (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/keysutil       (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/ldaputil       (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/locksutil      (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/logging        (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/ocsp   (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/pathmanager    (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/pluginutil     (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/policyutil     (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/roottoken      (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/salt   (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/shamir (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/stepwise       (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/template       (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/testhelpers    (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/testhelpers/schema     (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/useragent      (cached)
ok      github.com/openbao/openbao/sdk/v2/helper/xor    (cached)
ok      github.com/openbao/openbao/sdk/v2/logical       (cached)
ok      github.com/openbao/openbao/sdk/v2/physical/file (cached)
ok      github.com/openbao/openbao/sdk/v2/physical/inmem        (cached)
ok      github.com/openbao/openbao/sdk/v2/plugin        (cached)
ok      github.com/openbao/openbao/sdk/v2/plugin/mock   (cached)
ok      github.com/openbao/openbao/sdk/v2/plugin/pb     (cached)
ok      github.com/openbao/openbao/sdk/v2/queue (cached)
```

</details>

```
FAIL
make: *** [test] Error 1
```

**Expected behavior**
`Make test` exits with exit status 0

**Environment:**
* OpenBao Server Version:  **2.0.0-HEAD**
* OpenBao CLI Version: **OpenBao v2.0.0-HEAD ('e6c8d4fd69a06b3e8d8a8a9e88dcc9e122ef176b+CHANGES'), built 2024-09-23T11:59:34Z**
* Server Operating System/Architecture: **M1 running macOS Sonoma Version 14.6.1 (23G93)**
* go version: **go1.23.1 darwin/arm64**
* docker version: **Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13**

**Additional context**
I tried running the mysql tests on a local docker container incase the error was from incompatibility but I've had no luck with this. 

The reason I thought that would work was because the influxdb tests were also failing but after I pulled a local docker image from https://hub.docker.com/r/arm64v8/influxdb/ and altered in */openbao/plugins/database/influxdb/influxdb_test.go*:

From:
```
ImageRepo:     "docker.mirror.hashicorp.services/influxdb",
		ContainerName: "influxdb",
		ImageTag:      "1.8-alpine",
```

To match my container details: 
```
ImageRepo:     "influxdb",
		ContainerName: "influxdb",
		ImageTag:      "1.8"
```

Then the influxdb tests did not fail. I am new to openbao and open source in general so any help or tips will be greatly appreciated :)

### PR DESCRIPTION
**Pull request by fatima2003**
I upgraded the mysql version from 5.7 to 9.0 and changed the influxdb version to 1.8 from 1.8-alpine due to incompatibility with Apple Silicon M1 architecture. 

Resolves #552

## Target Release

1.14.7

### CODE REVIEW

**Comment by fatima2003** [comment]
I didn't sign off my commits, I fixing that now, sos

**Comment by cipherboy** [comment]
\o Hey @fatima2003: I'd suggest doing an interactive rebase as you can't DCO sign-off commits with merge updates.

Perhaps:

```
$ git rebase -i main
```

and change the list to:

```
pick 8b8ef66761 upgrade mysql docker version
break
pick faa85f56a6 Change InfluxDB version from 1.8-alpine to 1.8
break
```

(save and exit)

Then you can `git commit --amend -s` to add the sign-off, then do a `git rebase --continue`, and then do the same thing again (amend + continue) for the second commit.

**Comment by fatima2003** [comment]
Hi, I went ahead and made the changes. The DCO check now shows as successful, so I hope everything is in order.

**Comment by cipherboy** [comment]
@JanMa I realize the `Ensure Verified Commits / Verify Commit Signatures` workflow doesn't work well when other users use merge commits to update their branch... Thoughts?

**Comment by JanMa** [comment]
> @JanMa I realize the `Ensure Verified Commits / Verify Commit Signatures` workflow doesn't work well when other users use merge commits to update their branch... Thoughts?

I noticed this as well. Currently the workflow checks who authored the commit and not who committed it. I think it should work as intended if we switch that

**Comment by cipherboy** [comment]
@JanMa said:
> I noticed this as well. Currently the workflow checks who authored the commit and not who committed it. I think it should work as intended if we switch that

Hmm, on second thought, maybe it is working as intended? While I agree I think that would fix it in this case, one of the things I think we were trying to avoid was others impersonating our maintainers. I think this actually qualifies: the commit is a rebase of my commit from `main` and the merge commit actually isn't one (meaning my commit has a different hash, which could mean different contents).

Fixing this to allow just this case, I think, gets to be rather challenging.

---

@fatima2003 Out of curiosity, how'd you update the PR? It looks kinda like you rebased the head of `main` (56103d47f12d47679f94b11cf24f03b3775fd5cf) on top of your PR... And then allowed an empty merge commit with a single parent...?



All said, if @JanMa is fine with it, I'll just override the check and squash merge as usual. :-)

**Comment by fatima2003** [comment]
This is how I did things: I committed my first file (mysql test) I was sure of, then as I was testing the changes (for influxdb tests), main was updated so I synced changes. I then committed my second file. I realized I didn't sign off my commits so I rebased and included my signature like so: 

`git rebase HEAD~3 --signoff`

`git push --force-with-lease origin my_first_pr`

The DCO check passed after this. These instructions were available in the DCO check as a suggestion, I can't see this now that the check passes. 

I then followed this suggestion (in an attempt to pass _Ensure Verified Commits / Verify Commit Signatures (pull_request)_): 

> 
> ```
> $ git rebase -i main
> ```
> 
> and change the list to:
> 
> ```
> pick 8b8ef66761 upgrade mysql docker version
> break
> pick faa85f56a6 Change InfluxDB version from 1.8-alpine to 1.8
> break
> ```
> 
> (save and exit)
> 
> Then you can `git commit --amend -s` to add the sign-off, then do a `git rebase --continue`, and then do the same thing again (amend + continue) for the second commit.

**Comment by JanMa** [comment]
@cipherboy It's fine for me if you admin-merge this PR and I'll revisit the failing workflow afterwards :+1:

**Review by cipherboy — APPROVED** [review]

**Comment by cipherboy** [comment]
@fatima2003 Huh, no clue! :D I might've just given bad advice and misread the error. I think the rebase I proposed was necessary for dropping the merge commits, but didn't work with the state of the branch.

At any rate, it isn't a problem in this case, more a curiosity. Your steps look perfectly reasonable, though I'm dubious of the "update branch" button now so I've disabled it for the time being.

Thank you again!

**Comment by fatima2003** [comment]
Ah, no worries at all! I appreciate the guidance, it helped me better understand the process. I agree, disabling the 'update branch' button might avoid any further hiccups for now.

**Pull request merged**
