### PR TITLE
Remove the Redis database plugin

### PR DESCRIPTION
**Pull request by cipherboy**
Today Redis announced that it will no longer be licensed under an OSI-approved license and instead is dual licensed under the RSALv2 (Redis Source Available License v2) and the SSPLv1 (Server-Side Public License v1), instead of under the BSD 3-clause license.

Neither of these are OSI approved licenses, and thus per criteria in the plugin discussion (#64), this slates Redis for removal from the core binary.

See also: https://redis.com/blog/redis-adopts-dual-source-available-licensing/
See also: https://opensource.org/blog/the-sspl-is-not-an-open-source-license
See also: https://opensource.org/licenses

### CODE REVIEW

**Comment by cipherboy** [comment]
@naphelps this should be good to go.

**Review by JanMa — APPROVED** [review]
I am not happy about this change, but it is in line with what we decided in our plugin policy :-(

**Review by naphelps — APPROVED** [review]

**Comment by pdecat** [comment]
FWIW: [Redict is an independent, copyleft fork of Redis](https://redict.io/posts/2024-03-22-redict-is-an-independent-fork/)

**Comment by cipherboy** [comment]
@pdecat It looks like https://github.com/placeholderkv/placeholderkv is also a fork. I think we can re-introduce this once the forks stabilize, under the new name.

**Comment by pdecat** [comment]
[Placeholderkv](https://github.com/placeholderkv/placeholderkv) is now [valkey](https://github.com/valkey-io/valkey) 

https://www.linuxfoundation.org/press/linux-foundation-launches-open-source-valkey-community

**Pull request merged**
