### PR TITLE
docs(token): document the token format

### LINKED ISSUE #369: Document token format
**Is your feature request related to a problem? Please describe.**

I opened https://github.com/hashicorp/vault/issues/27151 and due to [legal shenanigans](https://github.com/hashicorp/vault/pull/27522#issuecomment-2174449065) ended up not contributing to `hashicorp/vault`

I was wondering if this project would benefits from clarification towards the token format.

It seems that the code used for generating it is similar to vault's: 

https://github.com/openbao/openbao/blob/180024468640acc82eb8dc621f7fd21ce6bfd125/vault/token_store.go#L997-L1000

Happy to discuss this further!

**Describe the solution you'd like**

Having the token format documented.

Here's [the patch](https://patch-diff.githubusercontent.com/raw/hashicorp/vault/pull/27522.patch) I submitted in `hashicorp/vault`, which might be applicable with little updates to this repo, granted the correct place is found.

```diff
+## Token formats
+
+Vault tokens are composed of a _prefix_ and a _body_.
+
+- The _prefix_ indicates the token's type:
+
+  Token Type | Vault 1.9.x or earlier | Vault 1.10 and later
+  -- | -- | --
+  Service tokens | s. | hvs.
+  Batch tokens | b. | hvb.
+  Recovery tokens | r. | hvr.
+
+- The _body_ is a randomly-generated 24 characters [Base62](https://en.wikipedia.org/wiki/Base62) string.
+
+Token are expected to match the following regexp: `(hv)?[sbr]\.[a-zA-Z0-9]{24}`
+
+Examples:
+
+```shell
+# Vault 1.9.x or earlier
+b.n6keuKu5Q6pXhaIcfnC9cFNd
+r.MEOkcS6xauDAZkS4bEvQTpbT
+
+# Vault 1.10 and later
+hvs.R0670sAqZnKX3yW40NddrPVk
+hvb.aYnhlZjetM09MRRc11FSLVk1
+```
+
```

**Additional context**

cc https://github.com/github/redacting-logger/pull/48
cc https://github.com/hashicorp/vault/issues/27151

### PR DESCRIPTION
**Pull request by nobe4**
Add details on the format of OpenBao tokens, it should hopefully add clear documentation as to one can detect tokens.

The body's format was inferred from:
- https://github.com/openbao/openbao/blob/180024468640acc82eb8dc621f7fd21ce6bfd125/vault/token_store.go#L72-L74
- https://github.com/openbao/openbao/blob/180024468640acc82eb8dc621f7fd21ce6bfd125/vault/token_store.go#L997-L999

Resolves #369 

## Target Release

1.14.7

### CODE REVIEW

**Review by cipherboy — APPROVED** [review]
Thank you!

**Comment by cipherboy** [comment]
@nobe4 Mind adding DCO `git commit --amend --signoff`? Thanks!

**Comment by nobe4** [comment]
@cipherboy, trying to do it at the moment, first time doing this 😬

**Comment by nobe4** [comment]
The DCO page was really helpful 👏 
https://github.com/openbao/openbao/pull/372/checks?check_run_id=26370274219

**Review by JanMa — APPROVED** [review]

**Pull request merged**
