### PR TITLE
PKI: Remove references to managed keys and enterprise no-ops functions

### PR DESCRIPTION
**Pull request by Gabrielopesantos**
## Description

This PR is a follow-up to https://github.com/openbao/openbao/pull/142, it removes the `managed_key_util.go` file from PKI, with no-ops enterprise functions and all of these functions.
Besides that, it also removes all references and usages of managed keys in the engine and SDK.

P.S: This PR has to be rebased once #142 is merged.

### CODE REVIEW

**Review by cipherboy — APPROVED** [review]
If you don't mind doing an interactive rebase, it'd be nice to drop both 46b9d99c7d5a261d81e9fead18c11947f4e24df9 and 4ef68b486f9828055a69c8af9407b21ca22af2ff, so we don't remove-and-re-add in the same PR since it won't be squashed. :-) 

Otherwise I think this looks good, thanks @Gabrielopesantos!!

**Comment by Gabrielopesantos** [comment]
> If you don't mind doing an interactive rebase, it'd be nice to drop both 46b9d99c7d5a261d81e9fead18c11947f4e24df9 and 4ef68b486f9828055a69c8af9407b21ca22af2ff, so we don't remove-and-re-add in the same PR since it won't be squashed. :-)
> 
> Otherwise I think this looks good, thanks @Gabrielopesantos!!

Sure, I couldn't find the objects (commits) you mentioned and rebased the branch with the main. Is that what you meant?

**Comment by cipherboy** [comment]
@Gabrielopesantos Feel free to skip the CL.

Sorry, not sure how I gave you such bogus commits lol. I meant the first and the last ones:

 - `a001bd5c3d6313a5c9567f8fed95d58a91dc5aa3` / `Remove IsEnterprise references` (modifies a single Transit file)
 - `9b178ba8ea1e596c948ae21d22d87594cc38aa2a` / `Revert deleted import in transit test` (undoes that modification).

**Comment by Gabrielopesantos** [comment]
> @Gabrielopesantos Feel free to skip the CL, I'm considering this all part of the initial "fork" changeset. I don't have labeling permissions and Nathan has been ignoring it :-)
> 
> Sorry, not sure how I gave you such bogus commits lol. I meant the first and the last ones:
> 
> * `a001bd5c3d6313a5c9567f8fed95d58a91dc5aa3` / `Remove IsEnterprise references` (modifies a single Transit file)
> * `9b178ba8ea1e596c948ae21d22d87594cc38aa2a` / `Revert deleted import in transit test` (undoes that modification).

Oh, I did not see that change was introduced in the first commit. Addressed. :+1:

**Review by cipherboy — APPROVED** [review]
Thank you @Gabrielopesantos!! Looks good to me :-) Want to try unified CRLs next?

**Review by naphelps — APPROVED** [review]

**Comment by naphelps** [comment]
@Gabrielopesantos As soon as you rebase this with updates, I will merge this one in. Thanks.

**Review by naphelps — APPROVED** [review]

**Pull request merged**
