### PR TITLE
UI: remove Vault references on signin page

### PR DESCRIPTION
**Pull request by bozzo**
Small part of #74

Replace the logo on the signin page and update the copyright

Capture d’écran 2024-10-20 à 12 58 18

### CODE REVIEW

**Review by JanMa — CHANGES_REQUESTED** [review]
Hey @bozzo thanks a lot for opening this PR. Can you please replace the logo with the new one which you can find in our [artwork repository](https://github.com/openbao/artwork)?

**Comment by bozzo** [comment]
@JanMa I've replaced the logos, I've also replaced the favicon. Here is the result:
Capture d’écran 2024-10-21 à 20 52 18

**Comment by bozzo** [comment]
I've a commit changing the logo on the sidebar, the splah screen and the loading, do you want me to add it to this PR or push it in a new PR?

**Comment by cipherboy** [comment]
@bozzo This PR works fine. :-)

**Review by JanMa — APPROVED** [review]

**Comment by cipherboy** [comment]
@bozzo I'll go ahead and merge this now, but feel free to open a follow-up for the sidebar logo updates!

**Pull request merged**
